export const GET_ARCHIVE_CUSTOMERS = "GET_ARCHIVE_CUSTOMERS"
export const GET_ARCHIVE_CUSTOMERS_PENDING = "GET_ARCHIVE_CUSTOMERS_PENDING"
export const GET_ARCHIVE_CUSTOMERS_FULFILLED = "GET_ARCHIVE_CUSTOMERS_FULFILLED"
export const GET_ARCHIVE_CUSTOMERS_REJECTED = "GET_ARCHIVE_CUSTOMERS_REJECTED"